services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017/?directConnection=true"
    volumes:
      - ./models/saved_models:/app/models/saved_models
      - ./uploaded:/app/uploaded
    networks:
      - app_network

  streamlit-frontend:
    build:
      context: .  # Assuming Streamlit is in the same directory as Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-backend
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge
