# version: '3.9'

# services:
#   fastapi-backend:
#     platform: linux/amd64
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     environment:
#       MONGO_URI: "mongodb://host.docker.internal:27017/?directConnection=true"
#     volumes:
#       - ./models/saved_models:/app/models/saved_models
#       - ./uploaded:/app/uploaded
#     networks:
#       - app_network

#   streamlit-frontend:
#     platform: linux/amd64
#     build:
#       context: .
#     ports:
#       - "8501:8501"
#     depends_on:
#       - fastapi-backend
#     networks:
#       - app_network

#   mongo:
#     image: mongo
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - app_network

# volumes:
#   mongo-data:

# networks:
#   app_network:
#     driver: bridge


version: '3.9'

services:
  fastapi-backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017/?directConnection=true"
    volumes:
      - ./models/saved_models:/app/models/saved_models
      - ./uploaded:/app/uploaded
    networks:
      - app_network

  streamlit-frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-backend
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge